// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

// AttributeModbusByteOrder specifies the value modbus.byte_order attribute.
type AttributeModbusByteOrder int

const (
	_ AttributeModbusByteOrder = iota
	AttributeModbusByteOrderABCD
	AttributeModbusByteOrderDCBA
	AttributeModbusByteOrderBADC
	AttributeModbusByteOrderCDAB
)

// String returns the string representation of the AttributeModbusByteOrder.
func (av AttributeModbusByteOrder) String() string {
	switch av {
	case AttributeModbusByteOrderABCD:
		return "ABCD"
	case AttributeModbusByteOrderDCBA:
		return "DCBA"
	case AttributeModbusByteOrderBADC:
		return "BADC"
	case AttributeModbusByteOrderCDAB:
		return "CDAB"
	}
	return ""
}

// MapAttributeModbusByteOrder is a helper map of string to AttributeModbusByteOrder attribute value.
var MapAttributeModbusByteOrder = map[string]AttributeModbusByteOrder{
	"ABCD": AttributeModbusByteOrderABCD,
	"DCBA": AttributeModbusByteOrderDCBA,
	"BADC": AttributeModbusByteOrderBADC,
	"CDAB": AttributeModbusByteOrderCDAB,
}

// AttributeModbusDataType specifies the value modbus.data_type attribute.
type AttributeModbusDataType int

const (
	_ AttributeModbusDataType = iota
	AttributeModbusDataTypeBool
	AttributeModbusDataTypeInt16
	AttributeModbusDataTypeInt32
	AttributeModbusDataTypeInt64
	AttributeModbusDataTypeUint16
	AttributeModbusDataTypeUint32
	AttributeModbusDataTypeUint64
	AttributeModbusDataTypeFloat32
	AttributeModbusDataTypeFloat64
)

// String returns the string representation of the AttributeModbusDataType.
func (av AttributeModbusDataType) String() string {
	switch av {
	case AttributeModbusDataTypeBool:
		return "bool"
	case AttributeModbusDataTypeInt16:
		return "int16"
	case AttributeModbusDataTypeInt32:
		return "int32"
	case AttributeModbusDataTypeInt64:
		return "int64"
	case AttributeModbusDataTypeUint16:
		return "uint16"
	case AttributeModbusDataTypeUint32:
		return "uint32"
	case AttributeModbusDataTypeUint64:
		return "uint64"
	case AttributeModbusDataTypeFloat32:
		return "float32"
	case AttributeModbusDataTypeFloat64:
		return "float64"
	}
	return ""
}

// MapAttributeModbusDataType is a helper map of string to AttributeModbusDataType attribute value.
var MapAttributeModbusDataType = map[string]AttributeModbusDataType{
	"bool":    AttributeModbusDataTypeBool,
	"int16":   AttributeModbusDataTypeInt16,
	"int32":   AttributeModbusDataTypeInt32,
	"int64":   AttributeModbusDataTypeInt64,
	"uint16":  AttributeModbusDataTypeUint16,
	"uint32":  AttributeModbusDataTypeUint32,
	"uint64":  AttributeModbusDataTypeUint64,
	"float32": AttributeModbusDataTypeFloat32,
	"float64": AttributeModbusDataTypeFloat64,
}

// AttributeModbusRegisterType specifies the value modbus.register_type attribute.
type AttributeModbusRegisterType int

const (
	_ AttributeModbusRegisterType = iota
	AttributeModbusRegisterTypeCoil
	AttributeModbusRegisterTypeDiscreteInput
	AttributeModbusRegisterTypeHoldingRegister
	AttributeModbusRegisterTypeInputRegister
)

// String returns the string representation of the AttributeModbusRegisterType.
func (av AttributeModbusRegisterType) String() string {
	switch av {
	case AttributeModbusRegisterTypeCoil:
		return "coil"
	case AttributeModbusRegisterTypeDiscreteInput:
		return "discrete_input"
	case AttributeModbusRegisterTypeHoldingRegister:
		return "holding_register"
	case AttributeModbusRegisterTypeInputRegister:
		return "input_register"
	}
	return ""
}

// MapAttributeModbusRegisterType is a helper map of string to AttributeModbusRegisterType attribute value.
var MapAttributeModbusRegisterType = map[string]AttributeModbusRegisterType{
	"coil":             AttributeModbusRegisterTypeCoil,
	"discrete_input":   AttributeModbusRegisterTypeDiscreteInput,
	"holding_register": AttributeModbusRegisterTypeHoldingRegister,
	"input_register":   AttributeModbusRegisterTypeInputRegister,
}

var MetricsInfo = metricsInfo{
	ModbusCoilValue: metricInfo{
		Name: "modbus.coil.value",
	},
	ModbusRegisterValue: metricInfo{
		Name: "modbus.register.value",
	},
}

type metricsInfo struct {
	ModbusCoilValue     metricInfo
	ModbusRegisterValue metricInfo
}

type metricInfo struct {
	Name string
}

type metricModbusCoilValue struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills modbus.coil.value metric with initial data.
func (m *metricModbusCoilValue) init() {
	m.data.SetName("modbus.coil.value")
	m.data.SetDescription("The value read from a Modbus coil or discrete input (0 or 1).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricModbusCoilValue) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, modbusNameAttributeValue string, modbusRegisterAddressAttributeValue int64, modbusRegisterTypeAttributeValue string, modbusUnitIDAttributeValue int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("modbus.name", modbusNameAttributeValue)
	dp.Attributes().PutInt("modbus.register_address", modbusRegisterAddressAttributeValue)
	dp.Attributes().PutStr("modbus.register_type", modbusRegisterTypeAttributeValue)
	dp.Attributes().PutInt("modbus.unit_id", modbusUnitIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricModbusCoilValue) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricModbusCoilValue) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricModbusCoilValue(cfg MetricConfig) metricModbusCoilValue {
	m := metricModbusCoilValue{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricModbusRegisterValue struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills modbus.register.value metric with initial data.
func (m *metricModbusRegisterValue) init() {
	m.data.SetName("modbus.register.value")
	m.data.SetDescription("The decoded value read from a Modbus holding or input register.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricModbusRegisterValue) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, modbusByteOrderAttributeValue string, modbusDataTypeAttributeValue string, modbusNameAttributeValue string, modbusRegisterAddressAttributeValue int64, modbusRegisterTypeAttributeValue string, modbusUnitIDAttributeValue int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("modbus.byte_order", modbusByteOrderAttributeValue)
	dp.Attributes().PutStr("modbus.data_type", modbusDataTypeAttributeValue)
	dp.Attributes().PutStr("modbus.name", modbusNameAttributeValue)
	dp.Attributes().PutInt("modbus.register_address", modbusRegisterAddressAttributeValue)
	dp.Attributes().PutStr("modbus.register_type", modbusRegisterTypeAttributeValue)
	dp.Attributes().PutInt("modbus.unit_id", modbusUnitIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricModbusRegisterValue) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricModbusRegisterValue) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricModbusRegisterValue(cfg MetricConfig) metricModbusRegisterValue {
	m := metricModbusRegisterValue{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                    MetricsBuilderConfig // config of the metrics builder.
	startTime                 pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity           int                  // maximum observed number of metrics per resource.
	metricsBuffer             pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                 component.BuildInfo  // contains version information.
	metricModbusCoilValue     metricModbusCoilValue
	metricModbusRegisterValue metricModbusRegisterValue
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                    mbc,
		startTime:                 pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:             pmetric.NewMetrics(),
		buildInfo:                 settings.BuildInfo,
		metricModbusCoilValue:     newMetricModbusCoilValue(mbc.Metrics.ModbusCoilValue),
		metricModbusRegisterValue: newMetricModbusRegisterValue(mbc.Metrics.ModbusRegisterValue),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricModbusCoilValue.emit(ils.Metrics())
	mb.metricModbusRegisterValue.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordModbusCoilValueDataPoint adds a data point to modbus.coil.value metric.
func (mb *MetricsBuilder) RecordModbusCoilValueDataPoint(ts pcommon.Timestamp, val int64, modbusNameAttributeValue string, modbusRegisterAddressAttributeValue int64, modbusRegisterTypeAttributeValue AttributeModbusRegisterType, modbusUnitIDAttributeValue int64) {
	mb.metricModbusCoilValue.recordDataPoint(mb.startTime, ts, val, modbusNameAttributeValue, modbusRegisterAddressAttributeValue, modbusRegisterTypeAttributeValue.String(), modbusUnitIDAttributeValue)
}

// RecordModbusRegisterValueDataPoint adds a data point to modbus.register.value metric.
func (mb *MetricsBuilder) RecordModbusRegisterValueDataPoint(ts pcommon.Timestamp, val float64, modbusByteOrderAttributeValue AttributeModbusByteOrder, modbusDataTypeAttributeValue AttributeModbusDataType, modbusNameAttributeValue string, modbusRegisterAddressAttributeValue int64, modbusRegisterTypeAttributeValue AttributeModbusRegisterType, modbusUnitIDAttributeValue int64) {
	mb.metricModbusRegisterValue.recordDataPoint(mb.startTime, ts, val, modbusByteOrderAttributeValue.String(), modbusDataTypeAttributeValue.String(), modbusNameAttributeValue, modbusRegisterAddressAttributeValue, modbusRegisterTypeAttributeValue.String(), modbusUnitIDAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
