// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for modbus metrics.
type MetricsConfig struct {
	ModbusCoilValue     MetricConfig `mapstructure:"modbus.coil.value"`
	ModbusRegisterValue MetricConfig `mapstructure:"modbus.register.value"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		ModbusCoilValue: MetricConfig{
			Enabled: true,
		},
		ModbusRegisterValue: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for modbus metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
