// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/ethernetip component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ethernetip")
	ScopeName = "github.com/otel-industrial/otel-industrial-resources/otel-industrial-collector/receiver/ethernetipreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
