// Code generated by mdatagen. DO NOT EDIT.

package ethernetipreceiver

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m, goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).Serve"), goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).serveTCP"), goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).serveUDP"))
}
