// Code generated by mdatagen. DO NOT EDIT.
//
// MANUALLY PATCHED: added goleak ignore options for the test-only
// gologix.Server instances started in client_test.go, which have no
// clean shutdown path (see startTestServer's comment). Re-apply this
// patch if metadata.yaml changes trigger a regeneration of this file.
package ethernetipreceiver

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m,
		goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).Serve"),
		goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).serveTCP"),
		goleak.IgnoreAnyFunction("github.com/danomagnum/gologix.(*Server).serveUDP"),
	)
}
